/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import java.sql.DriverManager;


/**
 *
 * @author Admin
 */
public class GUIGCUBake extends javax.swing.JFrame {
    
    //Global variables
    PreparedStatement pst = null;
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    GCUuser theUser; 
    GCUUser_Data_Handler UserHandler = new GCUUser_Data_Handler();
    

    /**
     * Creates new form GUIGCUBake
     */
    public GUIGCUBake() {
        initComponents();
        UserHandler.createDatabase();
        UserHandler.createTables();   
        
    }
    
    //had to add a duplicate of this method in order to get it to work
    protected void connection(){
        
        try{
        /* The details below may need to be adjust in order to connect on the local machine.
            Mysql database in combination with the mysql-connector-java.jar (added to library) file will be required
            in order to provide full functionality to the program and its database.
            
            */
        String mysqlUrl = "jdbc:mysql://localhost/GCUBake";
        String username = "root";
        String password = "Password";
        con = DriverManager.getConnection(mysqlUrl, username, password);
        }
        catch(Exception e){
            System.err.println("Got an exception");
            System.err.println(e.getMessage());
        
        }

        }
    //had to move this method into this class in order for it to work for some reason

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedGCUBake = new javax.swing.JTabbedPane();
        pnlRegister = new javax.swing.JPanel();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        cmdGender = new javax.swing.JComboBox<>();
        btnRegister = new javax.swing.JButton();
        pnlView = new javax.swing.JPanel();
        lblViewMessage = new javax.swing.JLabel();
        ComboView = new javax.swing.JComboBox();
        lblVLessonName = new javax.swing.JLabel();
        lblVName = new javax.swing.JLabel();
        lblVType = new javax.swing.JLabel();
        lblVStatus = new javax.swing.JLabel();
        txtVLessonID = new javax.swing.JTextField();
        txtVName = new javax.swing.JTextField();
        txtVType = new javax.swing.JTextField();
        txtVStatus = new javax.swing.JTextField();
        pnlBook = new javax.swing.JPanel();
        lblBookMessage = new javax.swing.JLabel();
        comboBook = new javax.swing.JComboBox();
        btnBook = new javax.swing.JButton();
        lblBookingConfirmation = new javax.swing.JLabel();
        pnlCreate = new javax.swing.JPanel();
        lblCName = new javax.swing.JLabel();
        lblCLessonID = new javax.swing.JLabel();
        txtCType = new javax.swing.JTextField();
        txtCLessonID = new javax.swing.JTextField();
        lblCStatus = new javax.swing.JLabel();
        txtCStatus = new javax.swing.JTextField();
        lblCType = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        lblCreateMessage = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        pnlEdit = new javax.swing.JPanel();
        lblEditMessage = new javax.swing.JLabel();
        ComboEdit = new javax.swing.JComboBox();
        lblELessonName = new javax.swing.JLabel();
        lblEName = new javax.swing.JLabel();
        lblEType = new javax.swing.JLabel();
        lblEStatus = new javax.swing.JLabel();
        txtELessonID = new javax.swing.JTextField();
        txtEName = new javax.swing.JTextField();
        txtEType = new javax.swing.JTextField();
        txtEStatus = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        pnlDelete = new javax.swing.JPanel();
        lblDeleteMessage = new javax.swing.JLabel();
        comboDelete = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        lblDeleteConfirmation = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStaffloginuser = new javax.swing.JTextField();
        txtStaffloginpass = new javax.swing.JTextField();
        btnStafflogin = new javax.swing.JButton();
        lblUserView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GCUBake");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });

        lblFirstName.setText("Firstname");

        lblLastName.setText("Lastname");

        lblEmail.setText("Email");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lblPhone.setText("Phone");

        lblTitle.setText("Title");

        lblUsername.setText("Username");

        lblPassword.setText("Password");

        cmdGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr", "Mrs", "Other" }));
        cmdGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGenderActionPerformed(evt);
            }
        });

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPhone)
                            .addComponent(lblEmail)
                            .addComponent(lblLastName)
                            .addComponent(lblFirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFirstname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(txtEmail)
                            .addComponent(txtLastname)
                            .addComponent(txtPhone))
                        .addGap(28, 28, 28)
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPassword)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(39, 39, 39)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdGender, 0, 200, Short.MAX_VALUE)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword))
                .addContainerGap())
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(cmdGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(lblUsername)
                            .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addGap(24, 24, 24))
        );

        TabbedGCUBake.addTab("Register", pnlRegister);

        pnlView.setName(""); // NOI18N
        pnlView.setRequestFocusEnabled(false);

        lblViewMessage.setText("Please select a lesson");

        ComboView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboViewActionPerformed(evt);
            }
        });

        lblVLessonName.setText("Lesson ID");

        lblVName.setText("Name");

        lblVType.setText("Type");

        lblVStatus.setText("Status");

        txtVStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVLessonName)
                            .addComponent(lblVName)
                            .addComponent(lblVType)
                            .addComponent(lblVStatus))
                        .addGap(64, 64, 64)
                        .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVType, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVLessonID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ComboView, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblViewMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblViewMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVLessonName)
                    .addComponent(txtVLessonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVName)
                    .addComponent(txtVName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVType)
                    .addComponent(txtVType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVStatus)
                    .addComponent(txtVStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        lblViewMessage.getAccessibleContext().setAccessibleName("view page");

        TabbedGCUBake.addTab("View Lesson", pnlView);

        lblBookMessage.setText("Please select which lesson you wish to book");

        btnBook.setText("Book Lesson");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBookLayout = new javax.swing.GroupLayout(pnlBook);
        pnlBook.setLayout(pnlBookLayout);
        pnlBookLayout.setHorizontalGroup(
            pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBookMessage)
                    .addComponent(comboBook, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBookLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBookingConfirmation)
                            .addComponent(btnBook))))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        pnlBookLayout.setVerticalGroup(
            pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblBookMessage)
                .addGap(18, 18, 18)
                .addComponent(comboBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnBook)
                .addGap(56, 56, 56)
                .addComponent(lblBookingConfirmation)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        TabbedGCUBake.addTab("Book Lesson", pnlBook);

        lblCName.setText("Name");

        lblCLessonID.setText("Lesson ID");

        lblCStatus.setText("Status");

        lblCType.setText("Type");

        lblCreateMessage.setText("Enter Lesson Details");

        btnCreate.setText("Create Lesson");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCreateLayout = new javax.swing.GroupLayout(pnlCreate);
        pnlCreate.setLayout(pnlCreateLayout);
        pnlCreateLayout.setHorizontalGroup(
            pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateMessage)
                    .addGroup(pnlCreateLayout.createSequentialGroup()
                        .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCLessonID)
                            .addComponent(lblCName)
                            .addComponent(lblCType)
                            .addComponent(lblCStatus))
                        .addGap(64, 64, 64)
                        .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCType, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCLessonID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreate))))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        pnlCreateLayout.setVerticalGroup(
            pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreateLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblCreateMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCLessonID)
                    .addComponent(txtCLessonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCName)
                    .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCType)
                    .addComponent(txtCType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCStatus)
                    .addComponent(txtCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnCreate)
                .addGap(22, 22, 22))
        );

        TabbedGCUBake.addTab("Create Lesson", pnlCreate);

        lblEditMessage.setText("Please select Lesson ID");

        ComboEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboEditActionPerformed(evt);
            }
        });

        lblELessonName.setText("Lesson ID");

        lblEName.setText("Name");

        lblEType.setText("Type");

        lblEStatus.setText("Status");

        txtEStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEStatusActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Lesson");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditLayout = new javax.swing.GroupLayout(pnlEdit);
        pnlEdit.setLayout(pnlEditLayout);
        pnlEditLayout.setHorizontalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblELessonName)
                            .addComponent(lblEName)
                            .addComponent(lblEType)
                            .addComponent(lblEStatus))
                        .addGap(64, 64, 64)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addComponent(txtEStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnEdit))
                            .addComponent(txtEType, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtELessonID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ComboEdit, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEditMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        pnlEditLayout.setVerticalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblEditMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblELessonName)
                    .addComponent(txtELessonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEName)
                    .addComponent(txtEName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEType)
                    .addComponent(txtEType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEStatus)
                            .addComponent(txtEStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit)
                        .addGap(28, 28, 28))))
        );

        TabbedGCUBake.addTab("Edit Lesson", pnlEdit);

        lblDeleteMessage.setText("Please select which lesson to cancel");

        btnDelete.setText("Cancel Lesson");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDeleteLayout = new javax.swing.GroupLayout(pnlDelete);
        pnlDelete.setLayout(pnlDeleteLayout);
        pnlDeleteLayout.setHorizontalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeleteMessage)
                            .addGroup(pnlDeleteLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(comboDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lblDeleteConfirmation)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        pnlDeleteLayout.setVerticalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblDeleteMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblDeleteConfirmation)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        TabbedGCUBake.addTab("Delete Lesson", pnlDelete);

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        txtStaffloginuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffloginuserActionPerformed(evt);
            }
        });

        btnStafflogin.setText("Login");
        btnStafflogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnStafflogin, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtStaffloginpass)
                            .addComponent(txtStaffloginuser))))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(txtStaffloginuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(txtStaffloginpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnStafflogin)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        TabbedGCUBake.addTab("Staff", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TabbedGCUBake, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lblUserView)
                .addGap(54, 54, 54)
                .addComponent(TabbedGCUBake, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        TabbedGCUBake.getAccessibleContext().setAccessibleName("View Lesson");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //test registering
        //register();
        //checklogin();
        //userDisplay();
       
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //place items in the comboDelete from database

        //collect selected item

        //call from Lesson_Data_Handler class in deleteLesson() method

        //confirmation given
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        //Edit lesson for the customer

        //get connection of database

        //display all of lesson id in the database in the

        //when selected place all fields in the textboxes as in the GUI

        //call from Lesson_Data_Handler class in editLesson() method

        //Confirmation given

    }//GEN-LAST:event_btnEditActionPerformed

    private void txtEStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEStatusActionPerformed

    private void ComboEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboEditActionPerformed

    }//GEN-LAST:event_ComboEditActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        //collects input data from te textboxes

        //calls the method in Lesson_Data_handler to createLesson()

        //Display confirmation of lesson
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        //booking lesson

        //customer selects which lesson by id from the database

        //btn clicked and calls method BookLesson()

        //shows a booking confirmation in the textbox called lblBookingconfirmation
        //followed by which lesson was booked by the customer

    }//GEN-LAST:event_btnBookActionPerformed

    private void txtVStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVStatusActionPerformed

    private void ComboViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboViewActionPerformed
        //viewing lesson for the customer

        //get connection of database

        //display all of lesson id in the database in the

        //when selected place all fields in the textboxes as in the GUI

    }//GEN-LAST:event_ComboViewActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        try{
            
            //create my mysql database connection
            connection();
            
            String query = "INSERT INTO User(customerStatus ,title, firstname, lastname, contactNo, email, username, password)" 
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(query);
            
            pst.setString(1,"Beginner");
            pst.setString(2,cmdGender.getSelectedItem().toString());
            pst.setString(3,txtFirstname.getText());
            pst.setString(4,txtLastname.getText());
            pst.setString(5,txtPhone.getText());
            pst.setString(6,txtEmail.getText());
            pst.setString(7,txtUsername.getText());
            pst.setString(8,txtPassword.getText());
            pst.execute();

            /* inserts the values username and password into a separate table in the database and
            makes use of the to ensure that the login is sercure(I will possibly make a change to
                how the structure of the databases work since there is an security issue here
                */
                String query2 = "INSERT INTO Login(username, password)" 
                        + "VALUES (?, ?)";
                pst = con.prepareStatement(query2);
                pst.setString(1,txtUsername.getText());
                pst.setString(2,txtPassword.getText());

                pst.execute();
                 
                
                JOptionPane.showMessageDialog(null, "Registration completed!");

                //reset registration boxes into empty text
                txtFirstname.setText("");
                txtLastname.setText("");
                txtPhone.setText("");
                txtEmail.setText("");
                txtUsername.setText("");
                txtPassword.setText("");

            }
            catch (Exception e){

                System.err.println("Got an exception");
                System.err.println(e.getMessage());
                JOptionPane.showMessageDialog(null, "Something went wrong try to register again");
                

            }
    }//GEN-LAST:event_btnRegisterActionPerformed

    
        
    private void cmdGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGenderActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmdGenderActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtStaffloginuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffloginuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffloginuserActionPerformed

    private void btnStaffloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffloginActionPerformed
        //this tab I implemented to ensure that staff has a separate login page from customer
          
        try{
        connection();
        String query ="SELECT * FROM Staff Where username='"+txtStaffloginuser.getText()+ "' and password='" +txtStaffloginpass.getText() + "'";
        pst=con.prepareStatement(query);
        rs=pst.executeQuery();
        
        
        if(rs.next()){
            JOptionPane.showMessageDialog(null, "Logged in as staff");
            this.dispose();
            
            
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            
            
            }                                        
        } 
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
            
            
        }
                                             
    }//GEN-LAST:event_btnStaffloginActionPerformed

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

     
    
    // Methods here
    
    
public void userDisplay(){
        GCUUser_Data_Handler myCheckAccount = new GCUUser_Data_Handler();
            myCheckAccount.checkUserIsValid(theUser);

            if (myCheckAccount.checkUserIsValid(theUser)){
                lblUserView.setText( theUser.getUsername());
            }
    }
    public void checklogin()
    {
        //programatically create the labels and texfields for the optionpane
        JLabel label_login = new JLabel("Username:");
        JTextField login = new JTextField();
        JLabel label_password = new JLabel("Password:");
        JPasswordField password = new JPasswordField();
        //-----------------------------------------------------
        // store these in an object array
        Object[] login_GUI_Elelemnts = {label_login, login, label_password, password};
        //-----------------------------------------------------
        int userInteraction = JOptionPane.showConfirmDialog(null, login_GUI_Elelemnts, "Login",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE);
        
        
        // this integer variable 'userInteraction' will hold the result of
        //the users interaction with the JOpttionPane
        //we will then test the result against common returned values. OK OPtion , Cancel , Closed
        //-----------------------------------------------------
        if (userInteraction == JOptionPane.OK_OPTION) {
            String user = login.getText().trim(); // user string that the user entered in the textfield
            String pass = new String(password.getPassword()); //pulls the password string from textfield
            Boolean entryGranted = false;// setup boolean as false.

            theUser = new GCUuser();
            theUser.setUsername(user); //Error shown here
            theUser.setPassCode(Integer.parseInt(pass));
            
            
            System.out.println("The users data is now " + theUser.toString());

            GCUUser_Data_Handler theUsersDataHandler = new GCUUser_Data_Handler();
            if (theUsersDataHandler.checkUserIsValid(theUser)) {
                theUser = theUsersDataHandler.getValidUser(theUser);
                System.out.println("The users data is now: " + theUser.toString());
            }

           //************************************Customer********************************* 
            if (theUser.getGcuRole().toUpperCase().equals("CUSTOMER")) {
                JOptionPane.showMessageDialog(this, "Logged in as Customer \nAll Chef and Admin panels will be removed");
                
                //If an ordinary user logged in then remove the panel tabs that relate to administrators.
                this.TabbedGCUBake.remove(pnlCreate); //removes the create tab
                this.TabbedGCUBake.remove(pnlEdit); //removes the edit tab
                this.TabbedGCUBake.remove(pnlDelete);// removes the delete tab
                
                entryGranted = true;
                
            }
            if (theUser.getGcuRole().toUpperCase().equals("CHEF")) {
                JOptionPane.showMessageDialog(this, "Logged in as Chef\nAccess granted to all areas");
                entryGranted = true;
            }
            if (!entryGranted) //entry denied
            {
                JOptionPane.showMessageDialog(this, "Entry Denied");
                userInteraction = JOptionPane.CANCEL_OPTION;
            }
        } else {//user clicked on CANCEL or the X close button- we change the userInteraction to force execution of the CANCEL block of code
            userInteraction = JOptionPane.CANCEL_OPTION;
        }
        if ((userInteraction == JOptionPane.CANCEL_OPTION) || (userInteraction == JOptionPane.CLOSED_OPTION)) // the cancel block of code - if user presses the X or CANCEL
        {
            //feedback to user and close the application as no suitable login credentials have been supplied.
            JOptionPane.showMessageDialog(this, "You have not supplied valid credentials\n the application will now terminate");
            System.exit(0);
        }

    }
    
    /*
    Notes for Register
    
    Register- fill out the textbox and taken to the login page
        already a member; where they will taken to the login form
    */
    public void register()
    {
        //programatically create the labels and texfields for the optionpane
        
        JLabel label_message = new JLabel("Please enter your details to register");
        
        JLabel label_login = new JLabel("Username:");
        JTextField login = new JTextField();
        
//-----------------------------------------------------
        // store these in an object array
        Object[] Register_GUI_Elelemnts = {label_login, login};
        /*-----------------------------------------------------buttons of the register page -
        Register- fill out the textbox and taken to the login page
        already a member; where they will taken to the login form
        
        
        */
        int userInteraction = JOptionPane.showConfirmDialog(null, Register_GUI_Elelemnts, "Register",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE);
        
    
    }




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIGCUBake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIGCUBake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIGCUBake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIGCUBake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIGCUBake().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboEdit;
    private javax.swing.JComboBox ComboView;
    private javax.swing.JTabbedPane TabbedGCUBake;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnStafflogin;
    private javax.swing.JComboBox<String> cmdGender;
    private javax.swing.JComboBox comboBook;
    private javax.swing.JComboBox comboDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBookMessage;
    private javax.swing.JLabel lblBookingConfirmation;
    private javax.swing.JLabel lblCLessonID;
    private javax.swing.JLabel lblCName;
    private javax.swing.JLabel lblCStatus;
    private javax.swing.JLabel lblCType;
    private javax.swing.JLabel lblCreateMessage;
    private javax.swing.JLabel lblDeleteConfirmation;
    private javax.swing.JLabel lblDeleteMessage;
    private javax.swing.JLabel lblELessonName;
    private javax.swing.JLabel lblEName;
    private javax.swing.JLabel lblEStatus;
    private javax.swing.JLabel lblEType;
    private javax.swing.JLabel lblEditMessage;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserView;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblVLessonName;
    private javax.swing.JLabel lblVName;
    private javax.swing.JLabel lblVStatus;
    private javax.swing.JLabel lblVType;
    private javax.swing.JLabel lblViewMessage;
    private javax.swing.JPanel pnlBook;
    private javax.swing.JPanel pnlCreate;
    private javax.swing.JPanel pnlDelete;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JPanel pnlView;
    private javax.swing.JTextField txtCLessonID;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCStatus;
    private javax.swing.JTextField txtCType;
    private javax.swing.JTextField txtELessonID;
    private javax.swing.JTextField txtEName;
    private javax.swing.JTextField txtEStatus;
    private javax.swing.JTextField txtEType;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtStaffloginpass;
    private javax.swing.JTextField txtStaffloginuser;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtVLessonID;
    private javax.swing.JTextField txtVName;
    private javax.swing.JTextField txtVStatus;
    private javax.swing.JTextField txtVType;
    // End of variables declaration//GEN-END:variables
}
