/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class GUIGCUBake extends javax.swing.JFrame {
    
    //Global variables
    
    GCUuser theUser; 
    GCUUser_Data_Handler UserHandler;

    /**
     * Creates new form GUIGCUBake
     */
    public GUIGCUBake() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedGCUBake = new javax.swing.JTabbedPane();
        pnlView = new javax.swing.JPanel();
        lblViewMessage = new javax.swing.JLabel();
        ComboView = new javax.swing.JComboBox();
        lblVLessonName = new javax.swing.JLabel();
        lblVName = new javax.swing.JLabel();
        lblVType = new javax.swing.JLabel();
        lblVStatus = new javax.swing.JLabel();
        txtVLessonID = new javax.swing.JTextField();
        txtVName = new javax.swing.JTextField();
        txtVType = new javax.swing.JTextField();
        txtVStatus = new javax.swing.JTextField();
        pnlBook = new javax.swing.JPanel();
        lblBookMessage = new javax.swing.JLabel();
        comboBook = new javax.swing.JComboBox();
        btnBook = new javax.swing.JButton();
        lblBookingConfirmation = new javax.swing.JLabel();
        pnlCreate = new javax.swing.JPanel();
        lblCName = new javax.swing.JLabel();
        lblCLessonID = new javax.swing.JLabel();
        txtCType = new javax.swing.JTextField();
        txtCLessonID = new javax.swing.JTextField();
        lblCStatus = new javax.swing.JLabel();
        txtCStatus = new javax.swing.JTextField();
        lblCType = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        lblCreateMessage = new javax.swing.JLabel();
        pnlEdit = new javax.swing.JPanel();
        lblEditMessage = new javax.swing.JLabel();
        ComboCreate = new javax.swing.JComboBox();
        lblELessonName = new javax.swing.JLabel();
        lblEName = new javax.swing.JLabel();
        lblEType = new javax.swing.JLabel();
        lblEStatus = new javax.swing.JLabel();
        txtELessonID = new javax.swing.JTextField();
        txtEName = new javax.swing.JTextField();
        txtEType = new javax.swing.JTextField();
        txtEStatus = new javax.swing.JTextField();
        pnlDelete = new javax.swing.JPanel();
        lblDeleteMessage = new javax.swing.JLabel();
        comboDelete = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        lblDeleteConfirmation = new javax.swing.JLabel();
        lblUserView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GCUBake");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlView.setName(""); // NOI18N
        pnlView.setRequestFocusEnabled(false);

        lblViewMessage.setText("Please select a lesson");

        lblVLessonName.setText("Lesson ID");

        lblVName.setText("Name");

        lblVType.setText("Type");

        lblVStatus.setText("Status");

        txtVStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVLessonName)
                            .addComponent(lblVName)
                            .addComponent(lblVType)
                            .addComponent(lblVStatus))
                        .addGap(64, 64, 64)
                        .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVType, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVLessonID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ComboView, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblViewMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblViewMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVLessonName)
                    .addComponent(txtVLessonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVName)
                    .addComponent(txtVName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVType)
                    .addComponent(txtVType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVStatus)
                    .addComponent(txtVStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        lblViewMessage.getAccessibleContext().setAccessibleName("view page");

        TabbedGCUBake.addTab("View Lesson", pnlView);

        lblBookMessage.setText("Please select which lesson you wish to book");

        btnBook.setText("Book Lesson");

        javax.swing.GroupLayout pnlBookLayout = new javax.swing.GroupLayout(pnlBook);
        pnlBook.setLayout(pnlBookLayout);
        pnlBookLayout.setHorizontalGroup(
            pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBookMessage)
                    .addComponent(comboBook, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBookLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBookingConfirmation)
                            .addComponent(btnBook))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        pnlBookLayout.setVerticalGroup(
            pnlBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblBookMessage)
                .addGap(18, 18, 18)
                .addComponent(comboBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnBook)
                .addGap(56, 56, 56)
                .addComponent(lblBookingConfirmation)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        TabbedGCUBake.addTab("Book Lesson", pnlBook);

        lblCName.setText("Name");

        lblCLessonID.setText("Lesson ID");

        lblCStatus.setText("Status");

        lblCType.setText("Type");

        lblCreateMessage.setText("Enter Lesson Details");

        javax.swing.GroupLayout pnlCreateLayout = new javax.swing.GroupLayout(pnlCreate);
        pnlCreate.setLayout(pnlCreateLayout);
        pnlCreateLayout.setHorizontalGroup(
            pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateMessage)
                    .addGroup(pnlCreateLayout.createSequentialGroup()
                        .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCLessonID)
                            .addComponent(lblCName)
                            .addComponent(lblCType)
                            .addComponent(lblCStatus))
                        .addGap(64, 64, 64)
                        .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCType, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCLessonID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        pnlCreateLayout.setVerticalGroup(
            pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreateLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblCreateMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCLessonID)
                    .addComponent(txtCLessonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCName)
                    .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCType)
                    .addComponent(txtCType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCStatus)
                    .addComponent(txtCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        TabbedGCUBake.addTab("Create Lesson", pnlCreate);

        lblEditMessage.setText("Please select Lesson ID");

        lblELessonName.setText("Lesson ID");

        lblEName.setText("Name");

        lblEType.setText("Type");

        lblEStatus.setText("Status");

        txtEStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditLayout = new javax.swing.GroupLayout(pnlEdit);
        pnlEdit.setLayout(pnlEditLayout);
        pnlEditLayout.setHorizontalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblELessonName)
                            .addComponent(lblEName)
                            .addComponent(lblEType)
                            .addComponent(lblEStatus))
                        .addGap(64, 64, 64)
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEType, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtELessonID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ComboCreate, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEditMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        pnlEditLayout.setVerticalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblEditMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblELessonName)
                    .addComponent(txtELessonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEName)
                    .addComponent(txtEName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEType)
                    .addComponent(txtEType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEStatus)
                    .addComponent(txtEStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        TabbedGCUBake.addTab("Edit Lesson", pnlEdit);

        lblDeleteMessage.setText("Please select which lesson to cancel");

        btnDelete.setText("Cancel Lesson");

        javax.swing.GroupLayout pnlDeleteLayout = new javax.swing.GroupLayout(pnlDelete);
        pnlDelete.setLayout(pnlDeleteLayout);
        pnlDeleteLayout.setHorizontalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDeleteMessage)
                            .addGroup(pnlDeleteLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(comboDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDeleteLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lblDeleteConfirmation)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        pnlDeleteLayout.setVerticalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblDeleteMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblDeleteConfirmation)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        TabbedGCUBake.addTab("Delete Lesson", pnlDelete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUserView))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(TabbedGCUBake, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblUserView)
                .addGap(54, 54, 54)
                .addComponent(TabbedGCUBake, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        TabbedGCUBake.getAccessibleContext().setAccessibleName("View Lesson");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //test registering
        //UserHandler.Register(theUser.test);
        
        //register();
        checklogin();
        userDisplay();
        
    }//GEN-LAST:event_formWindowOpened

    private void txtVStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVStatusActionPerformed

    private void txtEStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEStatusActionPerformed

    // Methods here
    
    
public void userDisplay(){
        GCUUser_Data_Handler myCheckAccount = new GCUUser_Data_Handler();
            myCheckAccount.checkUserIsValid(theUser);

            if (myCheckAccount.checkUserIsValid(theUser)){
                lblUserView.setText( theUser.getUsername());
            }
    }
    public void checklogin()
    {
        //programatically create the labels and texfields for the optionpane
        JLabel label_login = new JLabel("Username:");
        JTextField login = new JTextField();
        JLabel label_password = new JLabel("Password:");
        JPasswordField password = new JPasswordField();
        //-----------------------------------------------------
        // store these in an object array
        Object[] login_GUI_Elelemnts = {label_login, login, label_password, password};
        //-----------------------------------------------------
        int userInteraction = JOptionPane.showConfirmDialog(null, login_GUI_Elelemnts, "Login",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE);
        
        
        // this integer variable 'userInteraction' will hold the result of
        //the users interaction with the JOpttionPane
        //we will then test the result against common returned values. OK OPtion , Cancel , Closed
        //-----------------------------------------------------
        if (userInteraction == JOptionPane.OK_OPTION) {
            String user = login.getText().trim(); // user string that the user entered in the textfield
            String pass = new String(password.getPassword()); //pulls the password string from textfield
            Boolean entryGranted = false;// setup boolean as false.

           GCUuser  theUser = new GCUuser();
            theUser.setUsername(user);
            theUser.setPassCode(Integer.parseInt(pass));

            System.out.println("The users data is now " + theUser.toString());

            GCUUser_Data_Handler theUsersDataHandler = new GCUUser_Data_Handler();
            if (theUsersDataHandler.checkUserIsValid(theUser)) {
                theUser = theUsersDataHandler.getValidUser(theUser);
                System.out.println("The users data is now: " + theUser.toString());
            }

           //************************************Customer********************************* 
            if (theUser.getGcuRole().toUpperCase().equals("CUSTOMER")) {
                JOptionPane.showMessageDialog(this, "Logged in as Customer \nAll Chef and Admin panels will be removed");
                
                //If an ordinary user logged in then remove the panel tabs that relate to administrators.
                this.TabbedGCUBake.remove(pnlCreate); //removes the create tab
                this.TabbedGCUBake.remove(pnlEdit); //removes the edit tab
                this.TabbedGCUBake.remove(pnlDelete);// removes the delete tab
                
                entryGranted = true;
                
            }
            if (theUser.getGcuRole().toUpperCase().equals("CHEF")) {
                JOptionPane.showMessageDialog(this, "Logged in as Chef\nAccess granted to all areas");
                entryGranted = true;
            }
            if (!entryGranted) //entry denied
            {
                JOptionPane.showMessageDialog(this, "Entry Denied");
                userInteraction = JOptionPane.CANCEL_OPTION;
            }
        } else {//user clicked on CANCEL or the X close button- we change the userInteraction to force execution of the CANCEL block of code
            userInteraction = JOptionPane.CANCEL_OPTION;
        }
        if ((userInteraction == JOptionPane.CANCEL_OPTION) || (userInteraction == JOptionPane.CLOSED_OPTION)) // the cancel block of code - if user presses the X or CANCEL
        {
            //feedback to user and close the application as no suitable login credentials have been supplied.
            JOptionPane.showMessageDialog(this, "You have not supplied valid credentials\n the application will now terminate");
            System.exit(0);
        }

    }
    
    /*
    Notes for Register
    
    Register- fill out the textbox and taken to the login page
        already a member; where they will taken to the login form
    */
    public void register()
    {
        //programatically create the labels and texfields for the optionpane
        
        JLabel label_message = new JLabel("Please enter your details to register");
        
        JLabel label_login = new JLabel("Username:");
        JTextField login = new JTextField();
        
//-----------------------------------------------------
        // store these in an object array
        Object[] Register_GUI_Elelemnts = {label_login, login};
        /*-----------------------------------------------------buttons of the register page -
        Register- fill out the textbox and taken to the login page
        already a member; where they will taken to the login form
        
        
        */
        int userInteraction = JOptionPane.showConfirmDialog(null, Register_GUI_Elelemnts, "Register",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE);
        
    
    }




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIGCUBake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIGCUBake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIGCUBake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIGCUBake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIGCUBake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboCreate;
    private javax.swing.JComboBox ComboView;
    private javax.swing.JTabbedPane TabbedGCUBake;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox comboBook;
    private javax.swing.JComboBox comboDelete;
    private javax.swing.JLabel lblBookMessage;
    private javax.swing.JLabel lblBookingConfirmation;
    private javax.swing.JLabel lblCLessonID;
    private javax.swing.JLabel lblCName;
    private javax.swing.JLabel lblCStatus;
    private javax.swing.JLabel lblCType;
    private javax.swing.JLabel lblCreateMessage;
    private javax.swing.JLabel lblDeleteConfirmation;
    private javax.swing.JLabel lblDeleteMessage;
    private javax.swing.JLabel lblELessonName;
    private javax.swing.JLabel lblEName;
    private javax.swing.JLabel lblEStatus;
    private javax.swing.JLabel lblEType;
    private javax.swing.JLabel lblEditMessage;
    private javax.swing.JLabel lblUserView;
    private javax.swing.JLabel lblVLessonName;
    private javax.swing.JLabel lblVName;
    private javax.swing.JLabel lblVStatus;
    private javax.swing.JLabel lblVType;
    private javax.swing.JLabel lblViewMessage;
    private javax.swing.JPanel pnlBook;
    private javax.swing.JPanel pnlCreate;
    private javax.swing.JPanel pnlDelete;
    private javax.swing.JPanel pnlEdit;
    private javax.swing.JPanel pnlView;
    private javax.swing.JTextField txtCLessonID;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCStatus;
    private javax.swing.JTextField txtCType;
    private javax.swing.JTextField txtELessonID;
    private javax.swing.JTextField txtEName;
    private javax.swing.JTextField txtEStatus;
    private javax.swing.JTextField txtEType;
    private javax.swing.JTextField txtVLessonID;
    private javax.swing.JTextField txtVName;
    private javax.swing.JTextField txtVStatus;
    private javax.swing.JTextField txtVType;
    // End of variables declaration//GEN-END:variables
}
